<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <script>
      function divide(a, b) {
        if (b === 0) {
          throw '0으로는 나눌 수 없습니다.'
        }
        return a / b
      }

      console.log(divide(10, 2))
      console.log(divide(10, 0))
    </script>
  </head>
  <body>
  </body>
</html>

<!--
  예외 강제 발생
  상황에 따라서 예외를 강제로 발생시켜야 하는 경우도 있습니다. 예외를 강제로 발생시킬 때는
  throw 키워드를 사용합니다. throw 구문은 다음과 같은 형태로 사용합니다.

  // 단순하게 예외를 발생시킵니다.
  throw 문자열

  // 조금 더 자세하게 예외를 발생시킵니다.
  throw new Error(문자열)

  자바스크립트 콘솔에서 간단하게 사용해보겠습니다. throw 구문을 사용하면 곧바로 예외를 발생하는
  것을 볼 수 있습니다. 코드 실행 중에 throw 키워드를 사용하면 예외를 발생하므로 프로그램이
  중단됩니다.

  > throw '문자열'
  Uncaught 문자열

  > throw new Error('문자열')
  Uncaught Error: 문자열
    at 파일 이름 : 줄 번호

  단순하게 문자열을 입력한 경우와 new Error() 형태의 코드를 사용한 경우의 출력이 약간 다릅니다.

  예외를 강제로 발생시키는 이유는 무엇일까요? 일반적으로 개발할 때는 어떤 사람이 Lodash 라이브러리처럼
  다양한 기능을 가진 유틸리티 함수(또는 클래스)를 만들고, 다른 사람들이 그러한 라이브러리의 함수(또는 클래스)
  를 활용하는 경우가 많습니다.

  내가 만든 함수를 내가 사용할 때는 아무 문제없이 사용할 수 있겠지만, 내가 만든 함수를 다른 사람이 사용할 때는
  내가 의도하지 않은 형태로 코드를 사용할 수도 있습니다. 이럴 때 예외를 강제로 발생시키면 사용자에게
  주의를 줄 수 있으며, 의도한 대로 처리하게 유도할 수도 있습니다.
-->