1. 배열의 크기가 허용되는 크기 이상을 주고 예외 처리를 하자.
그리고 예외의 이름과 메세지를 출력하자.

풀이

      try {
        const array = new Array(999999999999999)
      } catch (exception) {
        console.log(exception)
        console.log()
        console.log(`예외 이름: ${exception.name}`)
        console.log(`예외 메시지: ${exception.message}`)
      }

2. 예외를 강제로 발생시킬때 throw 라는 키워드를 쓴다.
throw 키워드를 썼을 때 다음 두 가지 경우의 차이에 대해서 설명하자.

throw 문자열
throw new Error(문자열)

풀이
직접 실행해서 결과를 확인하자.
(throw1.html, throw2.html)


3. 예외가 강제로 발생되는 예시를 들어보자.

      function test(object) {
        if (object.a !== undefined && object.b !== undefined) {
          console.log(object.a + object.b)
        } else {
          throw new Error("a 속성과 b 속성을 지정하지 않았습니다.")
        }
      }

      test({})